### ISSUE TITLE
SendError on Seatalk

### ISSUE THREAD

**Issue by jeickmann** [AK-Homberger/Seatalk-Autopilot-Remote-Control#19]
Hi,

first of all, thanks for sharing this great project. I got everything setup and I am able to receive commands from the remote onto the pro micro. Unfortunatly, I seem to be unable to send anything on the seatalk bus, I always get "sendError".

Actually, I used the LED for debugging (turning it on on sendError and off when sendDatagram succeeeds), as somehow I can not get the serial monitor to work when connected to 12V and I do not have an OLED display set up.

Even just the regular sendDatagram calls for BeepOff cause this.

I checked the voltages and I get about 3,9 V / 0 Volt respectivly on the D1-Cathode when pulling Seatalk High or Low respectivly.

Any other ideas on what to debug?

Best and I really appreciate any help you can give.

Jan

**Comment by AK-Homberger** [comment]
You should test with 12 Volt and no connection to the Setalk-Bus first. As long as you get Send Errors then, it will not work because the board is not able to receive what it sends. You can also try a different  74LS07 device. It looks like some devices are not really LS devices (or CMOS equivalent).

**Comment by jeickmann** [comment]
Ok, thanks, good news that I can test without anything hooked up. Let me check tonight, I will also try to source a different 74LS07. I will report back.
